{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","text":"Overview","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"RevcontentSDK lets publishers embed Revcontent widgets in their SwiftUI apps with a single declarative view. The SDK handles widget rendering, content sizing, link interception, theme bridging, and impression-tracking coordination with the underlying JavaScript widget."}],"type":"paragraph"},{"anchor":"Quick-start","text":"Quick start","level":3,"type":"heading"},{"inlineContent":[{"type":"text","text":"Configure the SDK once at app launch:"}],"type":"paragraph"},{"syntax":"swift","code":["import RevcontentSDK","","@main","struct MyApp: App {","    init() {","        Revcontent.configure(","            publisherId: \"your-publisher-id\",","            siteUrl: \"https:\/\/your-site.example.com\"","        )","    }","","    var body: some Scene {","        WindowGroup { ContentView() }","    }","}"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"Drop an ad view into your content, and tag the enclosing "},{"type":"codeVoice","code":"ScrollView"},{"type":"text","text":" with "},{"type":"codeVoice","code":"revcontentScrollContext()"},{"type":"text","text":" so impression tracking works:"}],"type":"paragraph"},{"syntax":"swift","code":["ScrollView {","    VStack {","        ArticleBody()","","        RevcontentAdView(widgetId: \"your-widget-id\")","    }","    .revcontentScrollContext()","}"],"type":"codeListing"},{"content":[{"inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/SwiftUICore\/View\/revcontentScrollContext()","type":"reference","isActive":true},{"type":"text","text":" must be applied "},{"type":"strong","inlineContent":[{"text":"inside","type":"text"}]},{"type":"text","text":" the "},{"type":"codeVoice","code":"ScrollView"},{"type":"text","text":"’s content, not on the "},{"type":"codeVoice","code":"ScrollView"},{"type":"text","text":" itself. See "},{"identifier":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/ScrollContextPlacement","type":"reference","isActive":true},{"type":"text","text":" for the right and wrong way."}],"type":"paragraph"}],"style":"important","type":"aside","name":"Important"}]}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[[]]},"abstract":[{"type":"text","text":"Native SwiftUI integration for Revcontent ad widgets."}],"topicSections":[{"anchor":"Essentials","identifiers":["doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/Revcontent","doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/RevcontentAdView"],"title":"Essentials"},{"anchor":"Articles","identifiers":["doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/ScrollContextPlacement","doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/ThemeIntegration","doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/JSEventContract"],"title":"Articles"},{"anchor":"Explore-more-sheet","identifiers":["doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/ExploreMoreConfig","doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/FrequencyCapping"],"title":"Explore-more sheet"},{"anchor":"Link-handling","identifiers":["doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/LinkClickHandling"],"title":"Link handling"},{"anchor":"Extended-Modules","identifiers":["doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/SwiftUICore"],"title":"Extended Modules","generated":true}],"metadata":{"externalID":"RevcontentSDK","roleHeading":"Framework","symbolKind":"module","title":"RevcontentSDK","modules":[{"name":"RevcontentSDK"}],"role":"collection"},"identifier":{"url":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/revcontentsdk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/revcontentsdk"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.revcontent.RevcontentSDK/documentation/RevcontentSDK/LinkClickHandling":{"kind":"symbol","abstract":[{"text":"Return value for ","type":"text"},{"code":"RevcontentAdView.handleLinkClick(_:)","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Controls whether the SDK presents its default ","type":"text"},{"code":"SFSafariViewController","type":"codeVoice"},{"text":" ","type":"text"},{"text":"for the clicked link, or yields entirely to the publisher’s handler.","type":"text"}],"identifier":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/LinkClickHandling","type":"topic","url":"\/documentation\/revcontentsdk\/linkclickhandling","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LinkClickHandling"}],"title":"LinkClickHandling","navigatorTitle":[{"kind":"identifier","text":"LinkClickHandling"}]},"doc://com.revcontent.RevcontentSDK/documentation/RevcontentSDK/ThemeIntegration":{"identifier":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/ThemeIntegration","role":"collectionGroup","abstract":[{"type":"text","text":"Coordinate the widget’s appearance with your app’s color scheme."}],"kind":"article","type":"topic","title":"Theme integration","url":"\/documentation\/revcontentsdk\/themeintegration"},"doc://com.revcontent.RevcontentSDK/documentation/RevcontentSDK/FrequencyCapping":{"kind":"symbol","abstract":[{"type":"text","text":"Controls how frequently the explore-more sheet is shown to a user."}],"navigatorTitle":[{"text":"FrequencyCapping","kind":"identifier"}],"title":"FrequencyCapping","identifier":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/FrequencyCapping","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FrequencyCapping","kind":"identifier"}],"type":"topic","url":"\/documentation\/revcontentsdk\/frequencycapping"},"doc://com.revcontent.RevcontentSDK/documentation/RevcontentSDK/ExploreMoreConfig":{"url":"\/documentation\/revcontentsdk\/exploremoreconfig","navigatorTitle":[{"text":"ExploreMoreConfig","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration for the explore-more sheet, applied via the"},{"type":"text","text":" "},{"type":"codeVoice","code":".revcontentExploreMore(config:)"},{"type":"text","text":" modifier on an article view."}],"identifier":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/ExploreMoreConfig","title":"ExploreMoreConfig","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ExploreMoreConfig","kind":"identifier"}]},"doc://com.revcontent.RevcontentSDK/documentation/RevcontentSDK/RevcontentSDKVersionNumber":{"identifier":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/RevcontentSDKVersionNumber","role":"symbol","fragments":[{"text":"RevcontentSDKVersionNumber","kind":"identifier"}],"abstract":[{"type":"text","text":"Project version number for RevcontentSDK."}],"kind":"symbol","type":"topic","title":"RevcontentSDKVersionNumber","url":"\/documentation\/revcontentsdk\/revcontentsdkversionnumber"},"doc://com.revcontent.RevcontentSDK/documentation/RevcontentSDK/RevcontentSDKVersionString":{"title":"RevcontentSDKVersionString","type":"topic","role":"symbol","url":"\/documentation\/revcontentsdk\/revcontentsdkversionstring","fragments":[{"text":"RevcontentSDKVersionString","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/RevcontentSDKVersionString","abstract":[{"type":"text","text":"Project version string for RevcontentSDK."}]},"doc://com.revcontent.RevcontentSDK/documentation/RevcontentSDK/SwiftUICore/View/revcontentScrollContext()":{"conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" is ","type":"text"},{"code":"View","type":"codeVoice"},{"text":".","type":"text"}]},"title":"revcontentScrollContext()","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"revcontentScrollContext","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/SwiftUICore\/View\/revcontentScrollContext()","kind":"symbol","url":"\/documentation\/revcontentsdk\/swiftuicore\/view\/revcontentscrollcontext()","abstract":[{"text":"Marks this view’s enclosing ","type":"text"},{"code":"ScrollView","type":"codeVoice"},{"text":" as the scroll context for any","type":"text"},{"text":" ","type":"text"},{"code":"RevcontentAdView","type":"codeVoice"},{"text":" descendants.","type":"text"}]},"doc://com.revcontent.RevcontentSDK/documentation/RevcontentSDK/ScrollContextPlacement":{"title":"Scroll context placement","type":"topic","url":"\/documentation\/revcontentsdk\/scrollcontextplacement","abstract":[{"text":"Apply ","type":"text"},{"code":"revcontentScrollContext()","type":"codeVoice"},{"text":" inside the ","type":"text"},{"code":"ScrollView","type":"codeVoice"},{"text":"’s content, not on the ","type":"text"},{"code":"ScrollView","type":"codeVoice"},{"text":" itself.","type":"text"}],"identifier":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/ScrollContextPlacement","role":"collectionGroup","kind":"article"},"doc://com.revcontent.RevcontentSDK/documentation/RevcontentSDK/JSEventContract":{"type":"topic","role":"article","identifier":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/JSEventContract","kind":"article","abstract":[{"type":"text","text":"Events the SDK dispatches into the embedded widget, for widget JavaScript to consume."}],"title":"JavaScript event contract","url":"\/documentation\/revcontentsdk\/jseventcontract"},"doc://com.revcontent.RevcontentSDK/documentation/RevcontentSDK/Revcontent":{"title":"Revcontent","identifier":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/Revcontent","url":"\/documentation\/revcontentsdk\/revcontent","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Revcontent"}],"navigatorTitle":[{"kind":"identifier","text":"Revcontent"}],"abstract":[]},"doc://com.revcontent.RevcontentSDK/documentation/RevcontentSDK/RevcontentAdView":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RevcontentAdView","kind":"identifier"}],"identifier":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/RevcontentAdView","type":"topic","title":"RevcontentAdView","kind":"symbol","navigatorTitle":[{"text":"RevcontentAdView","kind":"identifier"}],"abstract":[{"type":"text","text":"A SwiftUI view that displays a Revcontent ad widget."}],"url":"\/documentation\/revcontentsdk\/revcontentadview","role":"symbol"},"doc://com.revcontent.RevcontentSDK/documentation/RevcontentSDK/SwiftUICore":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/SwiftUICore","abstract":[],"url":"\/documentation\/revcontentsdk\/swiftuicore","type":"topic","title":"SwiftUICore"},"doc://com.revcontent.RevcontentSDK/documentation/RevcontentSDK":{"url":"\/documentation\/revcontentsdk","identifier":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK","type":"topic","kind":"symbol","abstract":[{"text":"Native SwiftUI integration for Revcontent ad widgets.","type":"text"}],"title":"RevcontentSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"identifiers":["doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/ScrollContextPlacement","doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/ThemeIntegration","doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/JSEventContract"],"title":"Articles","anchor":"Articles"},{"identifiers":["doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/RevcontentSDKVersionNumber","doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/RevcontentSDKVersionString"],"generated":true,"title":"Variables","anchor":"Variables"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"}]}]}