{"kind":"article","seeAlsoSections":[{"generated":true,"title":"Articles","anchor":"Articles","identifiers":["doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/ScrollContextPlacement","doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/ThemeIntegration"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK"],["doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK","doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/ThemeIntegration"]]},"abstract":[{"text":"Events the SDK dispatches into the embedded widget, for widget JavaScript to consume.","type":"text"}],"variants":[{"paths":["\/documentation\/revcontentsdk\/jseventcontract"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/revcontentsdk\/jseventcontract"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"content","content":[{"level":2,"text":"Overview","anchor":"Overview","type":"heading"},{"inlineContent":[{"text":"RevcontentSDK communicates with the widget’s JavaScript by dispatching ","type":"text"},{"type":"codeVoice","code":"CustomEvent"},{"text":" instances on ","type":"text"},{"type":"codeVoice","code":"document"},{"text":". Each event is dispatched with ","type":"text"},{"type":"codeVoice","code":"bubbles: true, cancelable: true"},{"text":", and the payload is on ","type":"text"},{"type":"codeVoice","code":"event.detail"},{"text":".","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Widgets that want to participate in scroll-driven impression tracking or react to theme changes should add event listeners to "},{"type":"codeVoice","code":"document"},{"type":"text","text":" during their initialization."}],"type":"paragraph"},{"level":2,"text":"`revcontent:scroll`","anchor":"revcontentscroll","type":"heading"},{"inlineContent":[{"type":"text","text":"Dispatched on every scroll update from the host "},{"type":"codeVoice","code":"ScrollView"},{"type":"text","text":", throttled to ~30Hz with trailing coalescing. Also fired once immediately after the widget finishes loading, so the widget has initial geometry without waiting for the first scroll."}],"type":"paragraph"},{"inlineContent":[{"inlineContent":[{"type":"text","text":"Payload ("},{"type":"codeVoice","code":"event.detail"},{"type":"text","text":"):"}],"type":"strong"}],"type":"paragraph"},{"header":"row","rows":[[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Key"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Type"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Description"}]}]],[[{"type":"paragraph","inlineContent":[{"code":"rawOffset","type":"codeVoice"}]}],[{"type":"paragraph","inlineContent":[{"code":"Number","type":"codeVoice"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"The host scroll view’s current "},{"code":"contentOffset.y","type":"codeVoice"},{"type":"text","text":", in points."}]}]],[[{"type":"paragraph","inlineContent":[{"code":"contentOffset","type":"codeVoice"}]}],[{"type":"paragraph","inlineContent":[{"code":"Number","type":"codeVoice"}]}],[{"type":"paragraph","inlineContent":[{"code":"rawOffset + viewportHeight","type":"codeVoice"},{"text":". The y-coordinate, in the scroll view’s content space, of the bottom edge of the visible viewport.","type":"text"}]}]],[[{"type":"paragraph","inlineContent":[{"code":"isWidgetIntersecting","type":"codeVoice"}]}],[{"type":"paragraph","inlineContent":[{"code":"Boolean","type":"codeVoice"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether the widget’s frame currently intersects the visible viewport."}]}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"viewRect"}]}],[{"type":"paragraph","inlineContent":[{"code":"Object","type":"codeVoice"}]}],[{"type":"paragraph","inlineContent":[{"text":"The widget’s frame in the host scroll view’s coordinate space: ","type":"text"},{"type":"codeVoice","code":"{ x, y, width, height }"},{"text":", all numbers in points.","type":"text"}]}]]],"type":"table"},{"inlineContent":[{"inlineContent":[{"text":"Example listener:","type":"text"}],"type":"strong"}],"type":"paragraph"},{"syntax":"javascript","code":["document.addEventListener('revcontent:scroll', (event) => {","    const { isWidgetIntersecting, viewRect, contentOffset } = event.detail;","    if (isWidgetIntersecting) {","        \/\/ Widget is visible — fire viewability logic, mark impressions, etc.","    }","});"],"type":"codeListing"},{"level":2,"text":"`revcontent:theme`","anchor":"revcontenttheme","type":"heading"},{"inlineContent":[{"text":"Dispatched whenever the resolved SwiftUI color scheme changes. Fires at first load (after the widget finishes loading, if a scheme was already set) and on every subsequent change.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"inlineContent":[{"type":"text","text":"Payload ("},{"type":"codeVoice","code":"event.detail"},{"type":"text","text":"):"}],"type":"strong"}],"type":"paragraph"},{"type":"table","header":"row","rows":[[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Key"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Type"}]}],[{"type":"paragraph","inlineContent":[{"text":"Description","type":"text"}]}]],[[{"type":"paragraph","inlineContent":[{"code":"colorScheme","type":"codeVoice"}]}],[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"String"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Either "},{"type":"codeVoice","code":"\"dark\""},{"type":"text","text":" or "},{"type":"codeVoice","code":"\"light\""},{"type":"text","text":"."}]}]]]},{"inlineContent":[{"type":"strong","inlineContent":[{"text":"Example listener:","type":"text"}]}],"type":"paragraph"},{"syntax":"javascript","type":"codeListing","code":["document.addEventListener('revcontent:theme', (event) => {","    document.body.dataset.scheme = event.detail.colorScheme;","});"]},{"type":"aside","name":"Tip","content":[{"inlineContent":[{"text":"In most cases, CSS ","type":"text"},{"code":"@media (prefers-color-scheme: dark)","type":"codeVoice"},{"text":" already reacts correctly thanks to the SDK’s ","type":"text"},{"code":"overrideUserInterfaceStyle","type":"codeVoice"},{"text":" bridge. Only listen to this event if the widget needs imperative theme handling on top of CSS.","type":"text"}],"type":"paragraph"}],"style":"tip"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/JSEventContract"},"metadata":{"modules":[{"name":"RevcontentSDK"}],"role":"article","roleHeading":"Article","title":"JavaScript event contract"},"references":{"doc://com.revcontent.RevcontentSDK/documentation/RevcontentSDK/ScrollContextPlacement":{"title":"Scroll context placement","url":"\/documentation\/revcontentsdk\/scrollcontextplacement","type":"topic","identifier":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/ScrollContextPlacement","role":"collectionGroup","kind":"article","abstract":[{"type":"text","text":"Apply "},{"type":"codeVoice","code":"revcontentScrollContext()"},{"type":"text","text":" inside the "},{"type":"codeVoice","code":"ScrollView"},{"type":"text","text":"’s content, not on the "},{"type":"codeVoice","code":"ScrollView"},{"type":"text","text":" itself."}]},"doc://com.revcontent.RevcontentSDK/documentation/RevcontentSDK":{"abstract":[{"text":"Native SwiftUI integration for Revcontent ad widgets.","type":"text"}],"identifier":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK","type":"topic","url":"\/documentation\/revcontentsdk","title":"RevcontentSDK","role":"collection","kind":"symbol"},"doc://com.revcontent.RevcontentSDK/documentation/RevcontentSDK/ThemeIntegration":{"kind":"article","type":"topic","abstract":[{"text":"Coordinate the widget’s appearance with your app’s color scheme.","type":"text"}],"title":"Theme integration","url":"\/documentation\/revcontentsdk\/themeintegration","identifier":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/ThemeIntegration","role":"collectionGroup"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"replace","value":[{"anchor":"Articles","title":"Articles","identifiers":["doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/ScrollContextPlacement","doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/ThemeIntegration"],"generated":true}],"path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}