{"hierarchy":{"paths":[["doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK"]]},"sections":[],"primaryContentSections":[{"content":[{"type":"heading","text":"Overview","level":2,"anchor":"Overview"},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"RevcontentAdView"},{"text":" reports widget visibility back to the underlying widget JavaScript so impressions, viewability, and intersection events fire correctly. To do that, the SDK needs a reference to the enclosing ","type":"text"},{"type":"codeVoice","code":"UIScrollView"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/SwiftUICore\/View\/revcontentScrollContext()","type":"reference","isActive":true},{"type":"text","text":" modifier walks the view hierarchy at attach time to find that scroll view. It must be applied to a view that is "},{"inlineContent":[{"text":"inside","type":"text"}],"type":"emphasis"},{"type":"text","text":" the "},{"type":"codeVoice","code":"ScrollView"},{"type":"text","text":"’s content — not to the "},{"type":"codeVoice","code":"ScrollView"},{"type":"text","text":" itself, where it would walk the hierarchy "},{"inlineContent":[{"type":"text","text":"above"}],"type":"emphasis"},{"type":"text","text":" the scroll view and miss it."}]},{"type":"paragraph","inlineContent":[{"text":"Misplace the modifier and the SDK’s DEBUG assertions will fire immediately during development. In release, the SDK falls back to a warning and impression data will be missing or inaccurate.","type":"text"}]},{"type":"heading","text":"Right way","level":2,"anchor":"Right-way"},{"type":"paragraph","inlineContent":[{"text":"Apply the modifier to a view inside the ","type":"text"},{"code":"ScrollView","type":"codeVoice"},{"text":"’s content:","type":"text"}]},{"code":["ScrollView {","    VStack {","        ArticleBody()","        RevcontentAdView(widgetId: \"abc-123\")","    }","    .revcontentScrollContext()","}"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The modifier is on the "},{"type":"codeVoice","code":"VStack"},{"type":"text","text":", which is inside the "},{"type":"codeVoice","code":"ScrollView"},{"type":"text","text":". The finder walks up from the "},{"type":"codeVoice","code":"VStack"},{"type":"text","text":" and discovers the enclosing "},{"type":"codeVoice","code":"UIScrollView"},{"type":"text","text":"."}]},{"type":"heading","text":"Wrong way","level":2,"anchor":"Wrong-way"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Do not apply the modifier to the "},{"type":"codeVoice","code":"ScrollView"},{"type":"text","text":" itself:"}]},{"code":["\/\/ WRONG — finder walks above the ScrollView and finds nothing","ScrollView {","    VStack {","        ArticleBody()","        RevcontentAdView(widgetId: \"abc-123\")","    }","}",".revcontentScrollContext()"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Also wrong: forgetting the modifier entirely. The SDK provides a default empty scroll context as a fallback, so "},{"type":"codeVoice","code":"RevcontentAdView"},{"type":"text","text":" will still render — but no scroll-driven events will fire, and DEBUG builds will assert."}]},{"type":"heading","text":"Why this design","level":2,"anchor":"Why-this-design"},{"type":"paragraph","inlineContent":[{"text":"SwiftUI doesn’t expose the underlying ","type":"text"},{"code":"UIScrollView","type":"codeVoice"},{"text":" directly. The modifier installs a tiny invisible ","type":"text"},{"code":"UIView","type":"codeVoice"},{"text":" as a background, then walks up the superview chain at window-attachment time to locate the scroll view. Apply it inside the ","type":"text"},{"code":"ScrollView","type":"codeVoice"},{"text":"’s content for that walk to succeed.","type":"text"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/revcontentsdk\/scrollcontextplacement"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/revcontentsdk\/scrollcontextplacement"]}],"metadata":{"role":"collectionGroup","title":"Scroll context placement","modules":[{"name":"RevcontentSDK"}],"roleHeading":"API Collection"},"schemaVersion":{"major":0,"patch":0,"minor":3},"seeAlsoSections":[{"anchor":"Articles","identifiers":["doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/ThemeIntegration","doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/JSEventContract"],"title":"Articles","generated":true}],"kind":"article","identifier":{"url":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/ScrollContextPlacement","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Related-modifiers","identifiers":["doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/SwiftUICore\/View\/revcontentScrollContext()","doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/RevcontentAdView"],"title":"Related modifiers"}],"abstract":[{"text":"Apply ","type":"text"},{"type":"codeVoice","code":"revcontentScrollContext()"},{"text":" inside the ","type":"text"},{"type":"codeVoice","code":"ScrollView"},{"text":"’s content, not on the ","type":"text"},{"type":"codeVoice","code":"ScrollView"},{"text":" itself.","type":"text"}],"references":{"doc://com.revcontent.RevcontentSDK/documentation/RevcontentSDK/RevcontentAdView":{"title":"RevcontentAdView","navigatorTitle":[{"text":"RevcontentAdView","kind":"identifier"}],"identifier":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/RevcontentAdView","url":"\/documentation\/revcontentsdk\/revcontentadview","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RevcontentAdView","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"A SwiftUI view that displays a Revcontent ad widget.","type":"text"}]},"doc://com.revcontent.RevcontentSDK/documentation/RevcontentSDK/SwiftUICore/View/revcontentScrollContext()":{"identifier":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/SwiftUICore\/View\/revcontentScrollContext()","url":"\/documentation\/revcontentsdk\/swiftuicore\/view\/revcontentscrollcontext()","type":"topic","role":"symbol","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" is "},{"type":"codeVoice","code":"View"},{"type":"text","text":"."}]},"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"revcontentScrollContext"},{"kind":"text","text":"() -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"title":"revcontentScrollContext()","abstract":[{"type":"text","text":"Marks this view’s enclosing "},{"type":"codeVoice","code":"ScrollView"},{"type":"text","text":" as the scroll context for any"},{"type":"text","text":" "},{"code":"RevcontentAdView","type":"codeVoice"},{"type":"text","text":" descendants."}]},"doc://com.revcontent.RevcontentSDK/documentation/RevcontentSDK/ThemeIntegration":{"url":"\/documentation\/revcontentsdk\/themeintegration","type":"topic","abstract":[{"text":"Coordinate the widget’s appearance with your app’s color scheme.","type":"text"}],"kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/ThemeIntegration","title":"Theme integration"},"doc://com.revcontent.RevcontentSDK/documentation/RevcontentSDK":{"role":"collection","abstract":[{"text":"Native SwiftUI integration for Revcontent ad widgets.","type":"text"}],"type":"topic","url":"\/documentation\/revcontentsdk","kind":"symbol","identifier":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK","title":"RevcontentSDK"},"doc://com.revcontent.RevcontentSDK/documentation/RevcontentSDK/JSEventContract":{"title":"JavaScript event contract","role":"article","abstract":[{"type":"text","text":"Events the SDK dispatches into the embedded widget, for widget JavaScript to consume."}],"url":"\/documentation\/revcontentsdk\/jseventcontract","identifier":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/JSEventContract","type":"topic","kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"replace","path":"\/topicSections"},{"value":[{"title":"Articles","identifiers":["doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/ThemeIntegration","doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/JSEventContract"],"generated":true,"anchor":"Articles"}],"op":"replace","path":"\/seeAlsoSections"}]}]}