{"abstract":[{"text":"Coordinate the widget’s appearance with your app’s color scheme.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/ThemeIntegration","interfaceLanguage":"swift"},"metadata":{"title":"Theme integration","role":"collectionGroup","modules":[{"name":"RevcontentSDK"}],"roleHeading":"API Collection"},"primaryContentSections":[{"kind":"content","content":[{"level":2,"anchor":"Overview","type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"RevcontentSDK bridges SwiftUI’s color scheme into the embedded widget via two channels:","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The underlying "},{"type":"codeVoice","code":"WKWebView"},{"type":"text","text":"’s "},{"type":"codeVoice","code":"overrideUserInterfaceStyle"},{"type":"text","text":", so any CSS using "},{"type":"codeVoice","code":"@media (prefers-color-scheme: dark)"},{"type":"text","text":" resolves correctly."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"codeVoice","code":"revcontent:theme"},{"type":"text","text":" JavaScript event dispatched to the widget on change, so widget code can react explicitly."}]}]}],"type":"orderedList"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Both fire whenever the resolved SwiftUI color scheme changes — at first load and on every subsequent toggle."}]},{"level":2,"anchor":"Letting-the-widget-inherit-the-system-scheme","type":"heading","text":"Letting the widget inherit the system scheme"},{"type":"paragraph","inlineContent":[{"text":"By default, ","type":"text"},{"code":"RevcontentAdView","type":"codeVoice"},{"text":" inherits the color scheme from the SwiftUI environment, which is driven by the user’s system setting. No extra code required:","type":"text"}]},{"type":"codeListing","code":["RevcontentAdView(widgetId: \"abc-123\")"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"If the user toggles dark mode in Settings, the widget receives a ","type":"text"},{"code":"revcontent:theme","type":"codeVoice"},{"text":" event and its ","type":"text"},{"code":"overrideUserInterfaceStyle","type":"codeVoice"},{"text":" updates accordingly.","type":"text"}]},{"level":2,"anchor":"Forcing-a-specific-scheme","type":"heading","text":"Forcing a specific scheme"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Override the color scheme with the dedicated modifier:"}]},{"type":"codeListing","code":["RevcontentAdView(widgetId: \"abc-123\")","    .revcontentColorScheme(.dark)"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"This is equivalent to ","type":"text"},{"code":".environment(\\.colorScheme, .dark)","type":"codeVoice"},{"text":" but reads more clearly. Use it when you want the widget pinned to a specific appearance regardless of system setting — for example, inside an in-app reader that’s always dark.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can also use SwiftUI’s built-in "},{"type":"codeVoice","code":".preferredColorScheme(_:)"},{"type":"text","text":" higher up the view tree to set the scheme app-wide; the widget will follow."}]},{"level":2,"anchor":"What-the-widget-should-do","type":"heading","text":"What the widget should do"},{"type":"paragraph","inlineContent":[{"text":"The widget’s CSS and JavaScript should respect both bridge channels:","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"CSS","type":"text"}]},{"text":": use ","type":"text"},{"type":"codeVoice","code":"@media (prefers-color-scheme: dark) { ... }"},{"text":" for dark-mode styles. The SDK’s ","type":"text"},{"type":"codeVoice","code":"overrideUserInterfaceStyle"},{"text":" ensures this resolves correctly inside the ","type":"text"},{"type":"codeVoice","code":"WKWebView"},{"text":".","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"JavaScript"}],"type":"strong"},{"text":": optionally listen for ","type":"text"},{"code":"revcontent:theme","type":"codeVoice"},{"text":" events on ","type":"text"},{"code":"document","type":"codeVoice"},{"text":" if the widget needs to react imperatively. See ","type":"text"},{"identifier":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/JSEventContract","isActive":true,"type":"reference"},{"text":" for the payload shape.","type":"text"}]}]}],"type":"unorderedList"}]}],"kind":"article","hierarchy":{"paths":[["doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK"]]},"seeAlsoSections":[{"title":"Articles","generated":true,"identifiers":["doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/ScrollContextPlacement","doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/JSEventContract"],"anchor":"Articles"}],"topicSections":[{"title":"Related","identifiers":["doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/SwiftUICore\/View\/revcontentColorScheme(_:)","doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/JSEventContract"],"anchor":"Related"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/revcontentsdk\/themeintegration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/revcontentsdk\/themeintegration"]}],"references":{"doc://com.revcontent.RevcontentSDK/documentation/RevcontentSDK/JSEventContract":{"title":"JavaScript event contract","role":"article","abstract":[{"type":"text","text":"Events the SDK dispatches into the embedded widget, for widget JavaScript to consume."}],"url":"\/documentation\/revcontentsdk\/jseventcontract","identifier":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/JSEventContract","type":"topic","kind":"article"},"doc://com.revcontent.RevcontentSDK/documentation/RevcontentSDK":{"role":"collection","abstract":[{"text":"Native SwiftUI integration for Revcontent ad widgets.","type":"text"}],"type":"topic","url":"\/documentation\/revcontentsdk","kind":"symbol","identifier":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK","title":"RevcontentSDK"},"doc://com.revcontent.RevcontentSDK/documentation/RevcontentSDK/ScrollContextPlacement":{"kind":"article","url":"\/documentation\/revcontentsdk\/scrollcontextplacement","title":"Scroll context placement","identifier":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/ScrollContextPlacement","type":"topic","role":"collectionGroup","abstract":[{"type":"text","text":"Apply "},{"type":"codeVoice","code":"revcontentScrollContext()"},{"type":"text","text":" inside the "},{"type":"codeVoice","code":"ScrollView"},{"type":"text","text":"’s content, not on the "},{"type":"codeVoice","code":"ScrollView"},{"type":"text","text":" itself."}]},"doc://com.revcontent.RevcontentSDK/documentation/RevcontentSDK/SwiftUICore/View/revcontentColorScheme(_:)":{"url":"\/documentation\/revcontentsdk\/swiftuicore\/view\/revcontentcolorscheme(_:)","identifier":"doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/SwiftUICore\/View\/revcontentColorScheme(_:)","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Forces a specific color scheme on any "},{"type":"codeVoice","code":"RevcontentAdView"},{"type":"text","text":" descendants,"},{"text":" ","type":"text"},{"text":"overriding the system appearance.","type":"text"}],"title":"revcontentColorScheme(_:)","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" is "},{"code":"View","type":"codeVoice"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"revcontentColorScheme","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ColorScheme","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI11ColorSchemeO"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","op":"replace","value":[{"title":"Related","anchor":"Related","identifiers":["doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/JSEventContract"]}]},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"Articles","anchor":"Articles","identifiers":["doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/ScrollContextPlacement","doc:\/\/com.revcontent.RevcontentSDK\/documentation\/RevcontentSDK\/JSEventContract"],"generated":true}]}]}]}